import { useEffect, useState } from 'react';
const categories = ['Personal', 'Study', 'Projects', 'DSA', 'React', 'Important', 'Other'];
function NoteForm({ editingNote, onSubmit, onCancel }) {
  const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [category, setCategory] = useState('Personal'); const [error, setError] = useState('');
  useEffect(() => { setTitle(editingNote?.title || ''); setContent(editingNote?.content || ''); setCategory(editingNote?.category || 'Personal'); setError(''); }, [editingNote]);
  const handleSubmit = (event) => { event.preventDefault(); if (!title.trim() || !content.trim()) { setError('A title and a little content are both needed.'); return; } onSubmit({ title: title.trim(), content: content.trim(), category }); setTitle(''); setContent(''); setCategory('Personal'); setError(''); };
  return <form className="note-form" onSubmit={handleSubmit}><div className="form-top"><div className="field"><label htmlFor="note-title">Title</label><input id="note-title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Name this thought" /></div><div className="field category-field"><label htmlFor="note-category">Category</label><select id="note-category" value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="field"><label htmlFor="note-content">Content</label><textarea id="note-content" rows="5" value={content} onChange={(event) => setContent(event.target.value)} placeholder="Write something worth remembering..." /></div><div className="form-actions"><span className="form-error" role="alert">{error}</span>{editingNote && <button className="ghost-button" type="button" onClick={onCancel}>Cancel</button>}<button className="primary-button" type="submit">{editingNote ? 'Save note' : 'Create note'} <span>{editingNote ? '✓' : '+'}</span></button></div></form>;
}
export default NoteForm;
