import { useEffect, useState } from 'react';
import NoteForm from './components/NoteForm'; import NoteList from './components/NoteList'; import SearchBar from './components/SearchBar';
const STORAGE_KEY = 'minor-project-04-notes'; const THEME_KEY = 'minor-project-04-notes-theme';
function App() {
  const [notes, setNotes] = useState(() => JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]')); const [theme, setTheme] = useState(() => localStorage.getItem(THEME_KEY) || 'light'); const [searchTerm, setSearchTerm] = useState(''); const [editingNote, setEditingNote] = useState(null);
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(notes)); }, [notes]); useEffect(() => { localStorage.setItem(THEME_KEY, theme); document.documentElement.dataset.notesTheme = theme; }, [theme]);
  const handleSubmit = (noteData) => { const now = new Date().toISOString(); if (editingNote) { setNotes((current) => current.map((note) => note.id === editingNote.id ? { ...note, ...noteData, updatedAt: now } : note)); setEditingNote(null); return; } setNotes((current) => [{ ...noteData, id: crypto.randomUUID(), createdAt: now, updatedAt: now }, ...current]); };
  const handleDelete = (id) => { setNotes((current) => current.filter((note) => note.id !== id)); if (editingNote?.id === id) setEditingNote(null); };
  const filteredNotes = notes.filter((note) => `${note.title} ${note.content} ${note.category}`.toLowerCase().includes(searchTerm.toLowerCase()));
  return <div className="app-shell"><header className="topbar"><a className="brand" href="."><span className="brand-mark">✎</span><span>folio<span>.</span></span></a><div className="header-actions"><span className="header-count">{notes.length} {notes.length === 1 ? 'note' : 'notes'}</span><button className="theme-toggle" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label="Toggle light and dark mode">{theme === 'light' ? '☾ Dark mode' : '☀ Light mode'}</button></div></header><main className="main-content"><section className="hero-row"><div><p className="eyebrow">A PLACE FOR IDEAS</p><h1>Think it.<br /><em>Keep it.</em></h1><p className="intro-copy">Your digital commonplace book for the sparks, study notes, and half-formed ideas that deserve a little more time.</p></div><div className="hero-stamp"><span>EST.</span><strong>2026</strong><small>LOCAL FIRST</small></div></section><section className="workspace"><div className="workspace-heading"><div><p className="eyebrow">THE NOTEBOOK</p><h2>All your thoughts, together.</h2></div><SearchBar searchTerm={searchTerm} onSearch={setSearchTerm} /></div><NoteForm editingNote={editingNote} onSubmit={handleSubmit} onCancel={() => setEditingNote(null)} /><NoteList notes={filteredNotes} onEdit={setEditingNote} onDelete={handleDelete} hasSearch={Boolean(searchTerm)} /></section></main><footer><span>Built with React · Made for curious minds</span><span>Private by default</span></footer></div>;
}
export default App;
